### ISSUE TITLE
(BadRequestException) when calling the CreateRecommenderConfiguration operation

### ISSUE THREAD

**Issue by rvivier** [aws-samples/retail-demo-store#115]
Hi, 
I have encountered this error when running the  pinpoint.create_recommender_configuration cell in the 4.1-Pinpoint.ipynb notebook.

I solved it by adding "recommenders" to the SourceArn when authorizing Amazon Pinpoint to invoke the function.

I think the file below needs to be edited accordingly:
https://github.com/aws-samples/retail-demo-store/blob/master/aws/cloudformation-templates/services/pinpoint-personalize.yaml

SourceArn: !Sub 'arn:aws:mobiletargeting:${AWS::Region}:${AWS::AccountId}:**recommenders**/*'

**Comment by james-jory** [comment]
Thank you for raising this issue @rvivier. I just tested the Pinpoint notebook in a recently deployed instance of the project and the `create_recommender_configuration` cell completed successfully with the Lambda resource policy as-is. 

The change to the SourceArn that worked for you should have tightened the scope so I'm not sure how that would have resolved the issue. What region were you testing in?

**Comment by rvivier** [comment]
agreed, tbh I couldn't really explained why it wasn't working in the first place so went back to the documentation and tried to find differences in the configuration. 
that command is what made it work for me.
and the region was us-west-2.

aws lambda add-permission \
--function-name 'RetailDemoStorePinpointRecommender' \
--statement-id "RetailDemoStore-938483" \
--action 'lambda:InvokeFunction' \
--principal 'pinpoint.us-west-2.amazonaws.com' \
--source-arn 'arn:aws:mobiletargeting:us-west-2:_account_number_:recommenders/*'

**Comment by james-jory** [comment]
Closing since issue cannot be repeated.
