### ISSUE TITLE
Need help for old version

### ISSUE THREAD

**Issue by vivarma-1109** [aws-samples/retail-demo-store#180]
Hello Guys, 

can I get an old version of the site? because the existing S3 bucket is having a new code and a new format site. I am looking for an old format of the site. 

Also, are there any step-by-step instructions to add new a product to the site for testing the DevOps life cycle?

**Comment by james-jory** [comment]
Hi @vivarma-1109-

If you need an old version/snapshot of the repo, you can checkout from a particular commit.

https://githowto.com/getting_old_versions

You'll need to find the point in time that corresponds to the snapshot you're interested in. You can view the commit history here.

https://github.com/aws-samples/retail-demo-store/commits/master

As for adding new products to the project, that can be done a few ways. 

- For a new deployment, you can add products to the [products.yaml](https://github.com/aws-samples/retail-demo-store/blob/master/src/products/src/products-service/data/products.yaml) file and then deploy the project to your AWS account. For this to work, you will need to deploy from your own fork and staging bucket. Follow the [developer instructions](https://github.com/aws-samples/retail-demo-store/blob/master/Developer-Instructions.md) for this process.
- For an already deployed instance...
  - You can add products directly to the products DynamoDB table. Once added to DynamoDB, they products will show up on category pages but you will need to reindex the projects in Elasticsearch before your new products will show up in search results. The StartHere/Search workshop will step you through the indexing process.
  - You can add products using the Products service REST API. The `POST /products` endpoint can be used to add new products. You can get the host name for your deployed products service from the ELB console page in your AWS account. A tool like [Postman](https://www.postman.com/) can be used to make this easier than using `curl`.
