### ISSUE TITLE
What is the difference between _userauth.sign_in vs. UserSignedIn?

### ISSUE THREAD

**Issue by aeggbeg** [aws-samples/retail-demo-store#204]
Just wondering what is the difference between the following events

_userauth.sign_in vs. UserSignedIn - same goes for 3 __userauth.sign_up and _userauth.sign_out. Also to add what is the naming convention for Pinpoint Events to choose if I were to add more events. So far I have seen the following

_userauth.sign_in (new and duplicate)
Purchase event (extra space and e is not capitalised)
UserSignedIn (more common with other events)

Here is a quick view of all the events under pinpoint campaign screen.
<img width="967" alt="Screen Shot 2021-02-10 at 7 48 02 am" src="https://user-images.githubusercontent.com/77211680/107427349-6a146800-6b75-11eb-9af8-f905011cd872.png">

**Comment by aeggbeg** [comment]
Apologies this could be because I enabled cognito to talk to pinpoint. 
<img width="1124" alt="Screen Shot 2021-02-10 at 12 29 57 pm" src="https://user-images.githubusercontent.com/77211680/107451704-f33e9580-6b9b-11eb-892c-4429eb83828a.png">

**Comment by james-jory** [comment]
@aeggbeg, the event types that are prefixed with "_" are automatically generated by the Amplify client library (in coordination with Cognito for the "_userauth.*" events) and sent to Pinpoint. Pinpoint has a built-in understanding of these events for tracking sign-ins/outs, session start/stop, and monetization (purchases) to build its analytics dashboards and for using them for Pinpoint campaigns. 

The event types that are in camel-case (e.g. "CartViewed") are custom events emitted by the Retail Demo Store webapp itself. See the [AnalyticsHandler.js](https://github.com/aws-samples/retail-demo-store/blob/master/src/web-ui/src/analytics/AnalyticsHandler.js) for all events sent to Pinpoint and Personalize.
