### ISSUE TITLE
Is there a way to collect pinpoint event data from a plain HTML file e.g. via CDN include?

### ISSUE THREAD

**Issue by aeggbeg** [aws-samples/retail-demo-store#206]
Feedback from a customer meeting (with an existing ecommerce site) who wants to use pinpoint for abandon cart. It seems we need to use AWS Amplify/React/Vue to integrate pinpoint. Is there any documented approach to integrate pinpoint with a vanilla - plain HTML file - e.g. via CDN/Script SRC? 

I did come across some discussion/hack in AWS amplify issues in github - but nothing officially documented or best practice. I hope I have explained the problem correctly, keen to hear others experience/ways others have resolved it.

**Comment by james-jory** [comment]
Using Amplify is not a requirement. It just makes it easier to send events directly to Pinpoint from client application(s). For example, it tracks browser session termination to fire the session end event that can then be used to trigger an abandoned cart message. The customer could integrate directly with the AWS JS SDK to send client-side events or stream events to their own intermediary endpoint (APIGW -> Kinesis -> Lambda -> Pinpoint).

This is not the only way this can be done. For example, this can also be done server-side. Assuming the customer is tracking carts in a server-side datastore, they could periodically check for non-empty carts that have been inactive for a configurable amount of time and then fire an event to Pinpoint using the Pinpoint SDK to trigger the abandoned cart campaign.
