### ISSUE TITLE
Is Segment a requirement? 

### ISSUE THREAD

**Issue by aeggbeg** [aws-samples/retail-demo-store#214]
I don't have Segment and I didn't supply any segment key.
But the Cloudfrormation template still creates Segment Lambda Services? Is there other dependencies and that's the reason Segment lambda services gets created? How can I disable creating segment lambda services?

Thanks.

**Comment by james-jory** [comment]
Hi @aeggbeg. Segment is not required but the Lambda resources are deployed in case you activate the Segment integration by providing a write key after deployment. This is how 1:many workshops are delivered that show how to use Segment and Personalize together. Although the Lambdas are deployed, they are not invoked and are essentially disabled.
