### ISSUE TITLE
Setting Personalize SSM parameters do not appear to be getting picked up

### ISSUE THREAD

**Issue by bradaallen** [aws-samples/retail-demo-store#216]
Hi, I'm walking through the tutorial and can see that my campaigns are created and SSM parameters set.

However, when I go to the application - it does not appear the recommendations are being picked up. I did a hard reset and redeployed the Web UI to double check. Any suggestions for how to debug? I am also not seeing any events picked up by AWS Personalize.

A few pictures:
![image](https://user-images.githubusercontent.com/15333365/110142510-15869600-7d8b-11eb-9e0d-8dc71d26024e.png)
_campaigns and SSM parameters set_

![image](https://user-images.githubusercontent.com/15333365/110142739-57174100-7d8b-11eb-8ea8-69345641d7f0.png)
_UI not showing that the personalization service is getting picked up_

**Comment by james-jory** [comment]
Hi @bradaallen. It looks like you have everything setup correctly for the Recommendations service to pickup your campaign ARNs. A couple things to get check would be the logs for the Recommendations service to see if there are any errors or logging messages that could be helpful (you can find these under CloudWatch or ECS in the console). Also, do you have any active experiments running such as an A/B test? If so, you may be receiving the non-personalized control experience as part of the A/B split for an experiment. You would have had to run through one of the [experiment workshops](https://github.com/aws-samples/retail-demo-store/tree/master/workshop/3-Experimentation) for this to be the case.

**Comment by james-jory** [comment]
Hi @bradaallen. Any updates on this issue?

**Comment by bradaallen** [comment]
Hi @james-jory. I didn't try further debugging. I did, however, use the updated CloudFormation template and it ran beautifully. Thanks!
