### ISSUE TITLE
CloudFormation Deployment Issue CustomLaunchElasticsearchPreIndexLambdaFunction failed

### ISSUE THREAD

**Issue by hawjefferson** [aws-samples/retail-demo-store#254]
Tried to use the launch stack deployment and I'm getting this error when building the stack

Embedded stack arn:aws:cloudformation:us-east-1:903766178117:stack/retaildemostore-DeploymentSupport-JZP6DP99TCTV/97260a70-f63e-11eb-b35c-122e54527a47 was not successfully created: The following resource(s) failed to create: [CustomLaunchElasticsearchPreIndexLambdaFunction].

I'm setting Yes to all the AWS Personalised settings but not planning to use the optional items like Braze, Segment, etc..
![Screen Shot 2021-08-06 at 1 47 37 pm](https://user-images.githubusercontent.com/47293714/128453253-13d6a773-fdef-4d21-98ab-73cb0de3ea5d.png)

**Comment by james-jory** [comment]
Hi @hawjefferson. This issue was fixed earlier today with #253. You should be able to redeploy successfully now.

**Comment by hawjefferson** [comment]
Thanks @james-jory will test it out! Cheers!
