### ISSUE TITLE
Link to 3.2-AB-Experiment is broken in page https://github.com/aws-samples/retail-demo-store/blob/master/workshop/3-Experimentation/3.1-Overview.ipynb

### ISSUE THREAD

**Issue by battlebyte** [aws-samples/retail-demo-store#296]
Link to 3.2-AB-Experiment is broken at the bottom of the page page https://github.com/aws-samples/retail-demo-store/blob/master/workshop/3-Experimentation/3.1-Overview.ipynb.

Points to: https://notebooks.githubusercontent.com/view/3.2-AB-Experiment.ipynb
Should point to: https://github.com/aws-samples/retail-demo-store/blob/master/workshop/3-Experimentation/3.2-AB-Experiment.ipynb

**Comment by BastLeblanc** [comment]
Thanks for reporting.

I tried again, from github, the link points to https://github.com/aws-samples/retail-demo-store/blob/5edb237765e3f6ce68ada845c51311d3d1f1f270/workshop/3-Experimentation/3.2-AB-Experiment.ipynb

Which works, maybe a github issue

@battlebyte can you confirm?

Not sure why it didn't before

**Comment by battlebyte** [comment]
I confirm, it is working fine now.
