### ISSUE TITLE
CORS errors when loading home page after fresh deployment

### ISSUE THREAD

**Issue by melpais** [aws-samples/retail-demo-store#340]
Steps:
Make fresh deployment in Sydney region
Navigate to cloudfront distro
Login to home page

Error: Access to XMLHttpRequest at 'http://retai-loadb-???.ap-southeast-2.elb.amazonaws.com/rerank' from origin 'http://???.cloudfront.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by james-jory** [comment]
Fixed by #342
