### ISSUE TITLE
LocationNrfDemoLocationResourceStack Lambda fails when deploying via a staging S3 bucket with a path specified

### ISSUE THREAD

**Issue by paullepage** [aws-samples/retail-demo-store#344]
When deploying using a staging S3 bucket (per developer instructions), if an S3 path is used then the deployment fails when location services is enabled. This is because the LocationNrfDemoLocationResourceStack Lambda hasn't been written to cope with a path being used.

location.yaml line 65
location-resource-stack.py line 25

**Comment by BastLeblanc** [comment]
fixed ! thanks @paullepage for reporting
