### ISSUE TITLE
CloudFormation deploy fails because of AWSServiceRoleForAmazonOpenSearchService

### ISSUE THREAD

**Issue by Jon-AtAWS** [aws-samples/retail-demo-store#372]
I chose the 1-click deploy from the main project page, in Dublin. The stack does not deploy, and fails with 

"SLR [AWSServiceRoleForAmazonOpenSearchService] already exists but does not have a description. Please verify your SLR use case. If you are sure the use case is correct please modify your CloudFormation template and keep SLR description consistent."

The deploy should not fail if the role already exists.

**Comment by james-jory** [comment]
If you already have the OpenSearch SLR in your account, you should set the "Create OpenSearch Service Role?" parameter value to "No" as shown below.

![image](https://user-images.githubusercontent.com/1660965/176065746-2527cfa4-ed0f-438e-b5f9-236fc738a3dc.png)

This parameter can be found in the [root CFN template](https://github.com/aws-samples/retail-demo-store/blob/master/aws/cloudformation-templates/template.yaml#L179). You are looking in a nested template.
