### ISSUE TITLE
"Create Recommendations Email Template" section fails in messaging worksop - Amazon Pinpoint

### ISSUE THREAD

**Issue by kehirai8888** [aws-samples/retail-demo-store#413]
pinpoint.create_email_template command fails with following message.
> NameError: name 'recommender_id' is not defined

I found that "Create Personalized campaign" section was disappear in current version.

**Comment by Yazai** [comment]
The same here.
---
Create Recommendations Email Template
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_31666/2126841831.py in <cell line: 1>()
      3         'Subject': 'Retail Demo Store - Products Just for You',
      4         'TemplateDescription': 'Personalized recommendations email template',
----> 5         'RecommenderId': recommender_id,
      6         'HtmlPart': html_template,
      7         'TextPart': text_template,

NameError: name 'recommender_id' is not defined
