### ISSUE TITLE
Duplicate email welcome email and abandoned cart email 

### ISSUE THREAD

**Issue by kehirai8888** [aws-samples/retail-demo-store#425]
When I finished "Welcome Email" and "Load Abandoned Cart Email" sections in Amazon Pinpoint workshop, I can receive email but two email each.
https://github.com/aws-samples/retail-demo-store/blob/master/workshop/4-Messaging/4.1-Pinpoint.ipynb

**Comment by gfaires** [comment]
Should be fixed by #450 .  Please reopen if you continue to see problems
