### ISSUE TITLE
Cloudfront "Access Denied" when refreshing page outside of home page 

### ISSUE THREAD

**Issue by rwave-fluentcommerce** [aws-samples/retail-demo-store#456]
Hi team,

We've just recently deployed the latest stacks for the AWS retail demo store, and it looks great, however we notice that we can't refresh any pages outside of the home page.

Steps to reproduce: 
1. Deploy the Retail Demo Store to a new AWS account
2. Browse to the generated url for the retail demo store
![image](https://github.com/aws-samples/retail-demo-store/assets/138090241/32b8148c-7f11-41a7-b30e-941aed7c3f55)

3. Browse to one of the featured products
![image](https://github.com/aws-samples/retail-demo-store/assets/138090241/d717e591-8b8e-43de-be8d-728b9b3c5f72)

4. Refresh the current page

Expected behaviour:
1. Product page is reloaded successfully

Actual behaviour:
1. An "Access Denied" error is shown to the user
![image](https://github.com/aws-samples/retail-demo-store/assets/138090241/c507f19d-0ae6-49bf-ba1b-03828ac1cf56)

Note that this also happens on other pages - e.g if the auth page is refreshed.

**Comment by BastLeblanc** [comment]
Hi!
Thanks for raising this, can you confirm that you are using a recent version of the Retail Demo Store? Was it a fresh install ? 
We deployed large changes on moving to cloudfront https + api gateway, full on HTTPS recently (see PR #451)

Do you use the https cloudfront URL?
