### ISSUE TITLE
Retail Demo Store WebURL Returns Access Denied

### ISSUE THREAD

**Issue by CodyShive** [aws-samples/retail-demo-store#481]
After the CloudFormation stack is complete, the WebURL (https://d2fmgasm4hc3rg.cloudfront.net) throws an AccessDenied error.

**Comment by BastLeblanc** [comment]
the web-ui deployment is failing on npm ci complaining about package-lock not being synced.
Fixed in this #482 PR

**Comment by james-jory** [comment]
@BastLeblanc Can this be closed?
