### ISSUE TITLE
Typo "Serch" should be "Search"

### ISSUE THREAD

**Issue by bjvh** [aws-samples/retail-demo-store#492]
https://github.com/aws-samples/retail-demo-store/blob/b80137c6edb2c975c50221fcaba46b6abadd7b99/aws/cloudformation-templates/services/service/_template.yaml#L154

**Comment by AmineAouragh** [comment]
I just cloned the project and fixed the typo on a 'bugfixes' branch i created, just created a pull request a little bit earlier

**Comment by BastLeblanc** [comment]
this has been fixed along with other PR. Thanks for reporting !
