### ISSUE TITLE
Cloudformation Launch Template link isn't working

### ISSUE THREAD

**Issue by alannoun** [aws-samples/retail-demo-store#554]
I'm running into the issue of getting an access denied error when trying to launch the Cloudformation template. I've forked the repo and uploaded the template.yaml file as a work around but I still get the same error during the creation of the stack.

**Comment by BastLeblanc** [comment]
Hi, thanks for raising the issue.
Can you confirm you're following these instructions https://github.com/aws-samples/retail-demo-store/blob/master/Developer-Instructions.md ?

**Comment by alannoun** [comment]
> Hi, thanks for raising the issue. Can you confirm you're following these instructions https://github.com/aws-samples/retail-demo-store/blob/master/Developer-Instructions.md ?

Hello thank you for the timely response. I was able to upload everything to my personal S3 bucket by following the instructions, but I'm getting an error when deploying the cloudformation stack. The error seems to happen on the deployment-support.yaml file. Oddly enough, I can't find any Cloudwatch logs for this error on my account. The error is below:

CustomLaunchPersonalizePreCreateLambdaFunction CREATE_FAILED
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [2efa9972-1fb8-4172-9ba3-87541c9e3dee]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.


Is there any explanation for why this may be happening? If you can point me in the right direction I'd greatly appreciate it! Thanks

**Comment by BastLeblanc** [comment]
Can you look at the cloud watch logs of the lambda function that failed?

There was a recent bug that fixed in a latest PR

**Comment by BastLeblanc** [comment]
closing the issue but feel free to re-open if you still have the issue
