### ISSUE TITLE
Personalization demo fails to build

### ISSUE THREAD

**Issue by bobbruno** [aws-samples/retail-demo-store#57]
I just ran the Stackset on us-east-1, and the `WebUIPipeline` failed at the build stage. Apparently, the [lodash](https://lodash.com/) npm module is missing. I see it's been added to [`package.json`](https://github.com/aws-samples/retail-demo-store/blob/master/src/web-ui/package.json) a few days ago, but it doesn't show as installed in the build logs. I don't know npm well enough to understand what the sections in `packages.json` mean. 

For context, I ran the stackset on a clean Isengard account (my goal is to use this demo in a Personalize workshop), and while no cloudformation had any problem, I couldn't access the UI (access denied). Inspecting the stack, I saw the WebUIPipeline, and when I clicked on it, I saw a run that failed on the Build step. I'm assuming that's the cause of the problem. Here is my build log:

timestamp   | message
-------------|------------
1597073784712 | [Container] 2020/08/10 15:36:07 Waiting for agent ping
1597073784712 | [Container] 2020/08/10 15:36:09 Waiting for DOWNLOAD_SOURCE
1597073784712 | [Container] 2020/08/10 15:36:10 Phase is DOWNLOAD_SOURCE
1597073784712 | [Container] 2020/08/10 15:36:10 CODEBUILD_SRC_DIR=/codebuild/output/src889395199/src
1597073784712 | [Container] 2020/08/10 15:36:10 YAML location is /codebuild/output/src889395199/src/src/web-ui/buildspec.yml
1597073784712 | [Container] 2020/08/10 15:36:10 No commands found for phase name: install
1597073784712 | [Container] 2020/08/10 15:36:10 Processing environment variables
1597073784712 | [Container] 2020/08/10 15:36:10 Decrypting parameter store environment variables
1597073784712 | [Container] 2020/08/10 15:36:10 Selecting 'nodejs' runtime version '10' based on manual selections...
1597073784712 | [Container] 2020/08/10 15:36:10 Running command echo "Installing Node.js version 10 ..."
1597073784712 | Installing Node.js version 10 ...
1597073784712 |
1597073784712 | [Container] 2020/08/10 15:36:10 Running command n $NODE_10_VERSION
1597073784712 |    installed : v10.19.0 (with npm 6.13.4)
1597073784712 |
1597073784712 | [Container] 2020/08/10 15:36:20 Moving to directory /codebuild/output/src889395199/src
1597073784712 | [Container] 2020/08/10 15:36:20 Registering with agent
1597073784712 | [Container] 2020/08/10 15:36:20 Phases found in YAML: 4
1597073784712 | [Container] 2020/08/10 15:36:20  BUILD: 5 commands
1597073784712 | [Container] 2020/08/10 15:36:20  POST_BUILD: 4 commands
1597073784712 | [Container] 2020/08/10 15:36:20  INSTALL: 0 commands
1597073784712 | [Container] 2020/08/10 15:36:20  PRE_BUILD: 3 commands
1597073784712 | [Container] 2020/08/10 15:36:20 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
1597073784712 | [Container] 2020/08/10 15:36:20 Phase context status code:  Message:
1597073784712 | [Container] 2020/08/10 15:36:20 Entering phase INSTALL
1597073784712 | [Container] 2020/08/10 15:36:20 Phase complete: INSTALL State: SUCCEEDED
1597073784712 | [Container] 2020/08/10 15:36:20 Phase context status code:  Message:
1597073784712 | [Container] 2020/08/10 15:36:20 Entering phase PRE_BUILD
1597073784712 | [Container] 2020/08/10 15:36:20 Running command echo Installing NPM dependencies...
1597073784712 | Installing NPM dependencies...
1597073784712 |
1597073784712 | [Container] 2020/08/10 15:36:20 Running command cd src/web-ui
1597073784712 |
1597073784712 | [Container] 2020/08/10 15:36:20 Running command npm install
1597073784712 | npm WARN lifecycle retail-demo-store@0.1.0~preinstall: cannot run in wd retail-demo-store@0.1.0 npx npm-force-resolutions (wd=/codebuild/output/src889395199/src/src/web-ui)
1597073808763 |
1597073808763 | > yorkie@2.0.0 install /codebuild/output/src889395199/src/src/web-ui/node_modules/yorkie
1597073808763 | > node bin/install.js
1597073808763 |
1597073808763 | CI detected, skipping Git hooks installation
1597073808763 |
1597073808763 | > core-js@3.6.5 postinstall /codebuild/output/src889395199/src/src/web-ui/node_modules/core-js
1597073808763 | > node -e "try{require('./postinstall')}catch(e){}"
1597073808763 |
1597073808763 | [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
1597073808763 |
1597073808763 | [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
1597073808763 | [96m>[94m https://opencollective.com/core-js [0m
1597073808763 | [96m>[94m https://www.patreon.com/zloirock [0m
1597073808763 |
1597073808763 | [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
1597073808763 |
1597073808763 |
1597073808763 | > ejs@2.7.4 postinstall /codebuild/output/src889395199/src/src/web-ui/node_modules/ejs
1597073808763 | > node ./postinstall.js
1597073808763 |
1597073808763 | Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
1597073808763 |
1597073808763 |
1597073808763 | > fast-xml-parser@3.16.0 postinstall /codebuild/output/src889395199/src/src/web-ui/node_modules/fast-xml-parser
1597073808763 | > node tasks/postinstall.js || exit 0
1597073808763 |
1597073808763 | [96m[1mLove fast-xml-parser? Check [32mhttps://amitkumargupta.work [96m[1mfor more projects and contribution.[0m
1597073808763 |
1597073810801 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
1597073810801 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1597073810801 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
1597073810801 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1597073810801 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
1597073810801 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1597073810801 |
1597073810801 | added 1673 packages from 1345 contributors and audited 1677 packages in 27.869s
1597073810801 |
1597073810801 | 46 packages are looking for funding
1597073810801 |   run `npm fund` for details
1597073810801 |
1597073810801 | found 6 high severity vulnerabilities
1597073810801 |   run `npm audit fix` to fix them, or `npm audit` for details
1597073810801 |
1597073810801 | [Container] 2020/08/10 15:36:50 Phase complete: PRE_BUILD State: SUCCEEDED
1597073810801 | [Container] 2020/08/10 15:36:50 Phase context status code:  Message:
1597073810801 | [Container] 2020/08/10 15:36:50 Entering phase BUILD
1597073810801 | [Container] 2020/08/10 15:36:50 Running command chmod a+x ./gen_env.sh
1597073810801 |
1597073810801 | [Container] 2020/08/10 15:36:50 Running command rm .env
1597073810801 |
1597073810801 | [Container] 2020/08/10 15:36:50 Running command ./gen_env.sh
1597073810801 |
1597073810801 | [Container] 2020/08/10 15:36:50 Running command cat .env
1597073810801 | VUE_APP_PRODUCTS_SERVICE_DOMAIN=http://Retai-LoadB-11DYGPJ8JPZ6T-1035246880.us-east-1.elb.amazonaws.com
1597073810801 | VUE_APP_PRODUCTS_SERVICE_PORT=80
1597073810801 | VUE_APP_USERS_SERVICE_DOMAIN=http://Retai-LoadB-9ESFAWZ9S62E-1078856888.us-east-1.elb.amazonaws.com
1597073810801 | VUE_APP_USERS_SERVICE_PORT=80
1597073810801 | VUE_APP_CARTS_SERVICE_DOMAIN=http://Retai-LoadB-7P2APP8C63Z5-412475894.us-east-1.elb.amazonaws.com
1597073810801 | VUE_APP_CARTS_SERVICE_PORT=80
1597073810801 | VUE_APP_ORDERS_SERVICE_DOMAIN=http://Retai-LoadB-1UU45UGQPBSKB-1426193427.us-east-1.elb.amazonaws.com
1597073810801 | VUE_APP_ORDERS_SERVICE_PORT=80
1597073810801 | VUE_APP_RECOMMENDATIONS_SERVICE_DOMAIN=http://Retai-LoadB-OOAQW0U76ECE-618839683.us-east-1.elb.amazonaws.com
1597073810801 | VUE_APP_RECOMMENDATIONS_SERVICE_PORT=80
1597073810801 | VUE_APP_SEARCH_SERVICE_DOMAIN=http://Retai-LoadB-1HYTTD5RC70P7-493854681.us-east-1.elb.amazonaws.com
1597073810801 | VUE_APP_SEARCH_SERVICE_PORT=80
1597073810801 | VUE_APP_AWS_REGION=us-east-1
1597073810801 | VUE_APP_AWS_IDENTITY_POOL_ID=us-east-1:d611aae9-985d-449f-99fb-2fced5fb76f2
1597073810801 | VUE_APP_AWS_USER_POOL_ID=us-east-1_iEzajcHp0
1597073810801 | VUE_APP_AWS_USER_POOL_CLIENT_ID=6c9ru1cf1r7n7gp8quh01jf8l0
1597073810801 | VUE_APP_WEB_ROOT_URL=http://d2pwtxhbueegtu.cloudfront.net
1597073810801 | VUE_APP_IMAGE_ROOT_URL=http://d2pwtxhbueegtu.cloudfront.net/images/
1597073810801 | VUE_APP_BOT_NAME=RetailDemoStore
1597073810801 | VUE_APP_BOT_ALIAS=development
1597073810801 | VUE_APP_BOT_REGION=us-east-1
1597073810801 | VUE_APP_PINPOINT_APP_ID=edcb61be6f894f06b366577126e19303
1597073810801 | VUE_APP_PINPOINT_REGION=us-east-1
1597073810801 | VUE_APP_PERSONALIZE_TRACKING_ID=***
1597073810801 | VUE_APP_AMPLITUDE_API_KEY=***
1597073810801 |
1597073810801 | [Container] 2020/08/10 15:36:50 Running command npm run build
1597073810801 |
1597073810801 | > retail-demo-store@0.1.0 build /codebuild/output/src889395199/src/src/web-ui
1597073810801 | > vue-cli-service build
1597073810801 |
1597073812844 |
1597073812844 | -  Building for production...
1597073840896 |  ERROR  Failed to compile with 2 errors3:37:20 PM
1597073840896 |
1597073840896 | This dependency was not found:
1597073840896 |
1597073840896 | * lodash in ./node_modules/@aws-amplify/analytics/lib-esm/Providers/AmazonPersonalizeProvider.js, ./node_modules/@aws-amplify/analytics/lib-esm/Providers/AmazonPersonalizeHelper/SessionInfoManager.js
1597073840896 |
1597073840896 | To install it, you can run: npm install --save lodash
1597073840896 |  ERROR  Build failed with errors.
1597073840896 | npm ERR! code ELIFECYCLE
1597073840896 | npm ERR! errno 1
1597073840896 | npm ERR! retail-demo-store@0.1.0 build: `vue-cli-service build`
1597073840896 | npm ERR! Exit status 1
1597073840896 | npm ERR!
1597073840896 | npm ERR! Failed at the retail-demo-store@0.1.0 build script.
1597073840896 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
1597073840896 |
1597073840896 | npm ERR! A complete log of this run can be found in:
1597073840896 | npm ERR!     /root/.npm/_logs/2020-08-10T15_37_20_300Z-debug.log
1597073840896 |
1597073840896 | [Container] 2020/08/10 15:37:20 Command did not exit successfully npm run build exit status 1
1597073840896 | [Container] 2020/08/10 15:37:20 Phase complete: BUILD State: FAILED
1597073840896 | [Container] 2020/08/10 15:37:20 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run build. Reason: exit status 1
1597073840896 | [Container] 2020/08/10 15:37:20 Entering phase POST_BUILD
1597073840896 | [Container] 2020/08/10 15:37:20 Running command echo Uploading to ${WEB_BUCKET_NAME}
1597073840896 | Uploading to retaildemostore-base-e1p124khcs6m-clo-webuibucket-5pldu61svcjk
1597073840896 |
1597073840896 | [Container] 2020/08/10 15:37:20 Running command aws s3 cp --recursive ./dist s3://${WEB_BUCKET_NAME}/
1597073847210 |
1597073847210 | The user-provided path ./dist does not exist.
1597073847210 |
1597073847210 | [Container] 2020/08/10 15:37:25 Command did not exit successfully aws s3 cp --recursive ./dist s3://${WEB_BUCKET_NAME}/ exit status 255
1597073847210 | [Container] 2020/08/10 15:37:25 Phase complete: POST_BUILD State: FAILED
1597073847210 | [Container] 2020/08/10 15:37:25 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: aws s3 cp --recursive ./dist s3://${WEB_BUCKET_NAME}/. Reason: exit status 255
1597073847210 | [Container] 2020/08/10 15:37:25 Expanding base directory path: src/web-ui/dist
1597073847210 | [Container] 2020/08/10 15:37:25 Assembling file list
1597073847210 | [Container] 2020/08/10 15:37:25 Expanding src/web-ui/dist
1597073847210 | [Container] 2020/08/10 15:37:25 Skipping invalid file path src/web-ui/dist
1597073847210 | [Container] 2020/08/10 15:37:25 Phase complete: UPLOAD_ARTIFACTS State: FAILED
1597073847210 | [Container] 2020/08/10 15:37:25 Phase context status code: CLIENT_ERROR Message: no matching base directory path found for src/web-ui/dist

**Comment by james-jory** [comment]
Thanks, @bobbruno. Looks to be related to a recent upgrade to lodash that is incompatible with Amplify. For an immediate workaround, you can back out the following change while we investigate a longer term solution.

https://github.com/aws-samples/retail-demo-store/pull/53/commits/f7a3bc36f6063337884eda248cf8915ea336e63b
