### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by bebbo-zz** [aws-samples/retail-demo-store#570]
fatal: unable to access 'https://gopkg.in/yaml.v2/': Failed to connect to gopkg.in port 443 after 225004 ms: Couldn't connect to server

**Comment by BastLeblanc** [comment]
It looks like a temporary failure, can you try again?

Have you deployed in anything specific VPC / network setup?

**Comment by bebbo-zz** [comment]
Yes, after trying it again somehow it worked. sorry cannot give you more details.
