### ISSUE TITLE
Feature Request: align title and descriptions to the pictures

### ISSUE THREAD

**Issue by BastLeblanc** [aws-samples/retail-demo-store#602]
Currently the descriptions are generated but are not always aligned to the product picture.

Proposed work:

Loop through every product

1. upload the picture to Bedrock, Claude 3
2. prompt proposition: 

```
Identify the main object in this scene and generate a title and detailed product description for it, make it engaging for an e-commerce website.
Put your answer between tags
<title>
<description>
```

3. Modify products.yaml file

**Comment by julianbonilla** [comment]
@BastLeblanc I'd like to work on this feature request.  Can you assign it to me?

**Comment by BastLeblanc** [comment]
I've assigned it to you. Let us know how you progress.
As much as possible it would be good to build a reusable process (script/step function/s3 batch..) so we can reuse when we add more products or more pictures.
Maybe we can even think of just uploading new pictures and it will categorize and store a generated product info for it.

Thanks in advance for your contribution !

**Comment by BastLeblanc** [comment]
merged
