### ISSUE TITLE
Geeting error when deployed CFT templates.

### ISSUE THREAD

**Issue by shibearati** [aws-samples/retail-demo-store#603]
I am trying to create a CloudFormation stack using the provided template in this repository. However, I encountered an issue where certain parameters seem to be mandatory, and I receive the following error message when the values are not provided:

(**An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [ResourceBucketImages, mParticleApiKey, mParticleS2SSecretKey, GoogleAnalyticsMeasurementId, PinpointSMSLongCode, SegmentWriteKey, AmazonPayStoreId, mParticleOrgId, ResourceBucketImagesPrefix, AlexaSkillId, mParticleSecretKey, AmazonPayPublicKeyId, AmazonPayPrivateKey, mParticleS2SApiKey, PinpointEmailFromAddress, AmazonPayMerchantId, AlexaDefaultSandboxEmail, OptimizelySdkKey, GitHubToken, AmplitudeApiKey] must have values**)

**Steps to Reproduce**:

Attempt to create a CloudFormation stack without providing values for the mentioned parameters.
Observe the validation error.

**Questions:**

- Are these parameter values mandatory for the stack creation?
- If they are not mandatory, is there a way to set default values or make them optional in the CloudFormation template?
- If they are mandatory, could you please provide more details on how to obtain or generate the required values?
-

**Comment by BastLeblanc** [comment]
Hi thanks for reporting this issue.

These parameters didn't have any default values so cloudformation was expecting them. We haven't spotted this, via the console this is not required, and the deployment scripts had all the parameters.

That said, it is cleaner to have default value if the parameter is not required.
The only parameter required is ```ResourceBucket```

I've created a new PR #606 to fix this, could you test this PR and let us know if that fixes your issue?

**Comment by BastLeblanc** [comment]
PR merged
