### ISSUE TITLE
Misuse of the `cat` command in the ECS Immersion day training

### ISSUE THREAD

**Issue by cocojamb0** [aws-samples/retail-demo-store#610]
While running through the ECS Immersion day training, I noticed that the workshop studio guide contains what I believe to be misuse of the `cat` command.

`cat layout.html | grep CodePipeline`
can be achieved with the single command:
`grep CodePipeline layout.html`

<img width="632" alt="image" src="https://github.com/user-attachments/assets/ea70ae8f-2f74-4b9b-899b-51184215299d">

I wasn't sure where else to put this.

**Comment by BastLeblanc** [comment]
Thanks for reporting this. The ECS immersion day is actually using a different demo than this retail demo store, but I'm forwarding this request to the relevant team internally.
