### ISSUE TITLE
Add a service link role to Amazon OpenSearch Service

### ISSUE THREAD

**Issue by erikanagamine** [aws-samples/retail-demo-store#621]
On Step-by-step there is a mention of add a linked role to amazon opensearch service that is not present in IaC

**Comment by BastLeblanc** [comment]
Hi,

It is created as part of the cloudformation Template, here:
https://github.com/aws-samples/retail-demo-store/blob/193f65086843dd70410079f9f0a38e18163111ef/aws/cloudformation-templates/base/_template.yaml#L198

It is created based on the condition CreateOpenSearchServiceLinkedRole

Can you describe a bit more your issue?
