### ISSUE TITLE
Deploy failed due to CustomLoadDataProducts

### ISSUE THREAD

**Issue by jingnanl** [aws-samples/retail-demo-store#626]
I'm trying to deploy the solution with the latest code (commit a45530a) but failed.

> Status reason
> Embedded stack arn:aws:cloudformation:us-west-2:012870276471:stack/retaildemostore-DeploymentSupport-7F45MPQBWCLN/f7d34d10-66a2-11ef-b88d-069aa8cc439f was not successfully created: The following resource(s) failed to create: [CustomLoadDataProducts].

Look into the nested stack `DeploymentSupport`

> CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [86b3e845-2b18-4176-82dc-b911199661a7]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

Not sure if it's related to the recent change of [#624](https://github.com/aws-samples/retail-demo-store/pull/624/files).

**Comment by jingnanl** [comment]
I reverted back to the commit db49913 which doesn't include #624 change, the issue remains.

**Comment by BastLeblanc** [comment]
Hi,

This fails most probably because an underlying issue in deploying the products service.

To help debug the issue, can you look at and share :

- Any errors in the codepipeline, especially the products service
- Logs from cloudwatch logs of `/aws/lambda/<stack>-DeploymentSupport-<id>-LoadDataLambdaFunction-<id2>`
(names will differ, but will include LoadDataLambdaFunction)

How did you deploy the demo store? Any parameters did you change?

**Comment by jingnanl** [comment]
Hi,

It looks like the `ProductsService` nested stack was created successfully prior to the `DeploymentSupport` stack creation failure.

In the cloudwatch logs for `DeploymentS-LoadDataLambdaFunction`, I saw a lot of 404 errors
![image](https://github.com/user-attachments/assets/f7215299-707c-4d2a-b678-29029a009084)

I was using the CloudFormation template generated by the `./stage.sh` script to deploy the demo store. I've tried several times, with least services (only basic demo store) and most services (including Personalize and Pinpoint etc.), all failed. I was not using the default stack name, and I selected `S3` Deployment Type.

Thanks,

**Comment by jingnanl** [comment]
> Hi @jingnanl Can you go into CodePipeline? Are all the deployments showing successful? Pay special attention to the products service deployment too.

Previously I was using the CloudFormation template quick link, the `ProductsService` was rollback and deleted upon deployment failure, the nested stack didn't show any failure. This time I deployed the template manually with auto rollback disabled and I saw all the CodePipelines were failed due to s3 bucket not versioned.
![image](https://github.com/user-attachments/assets/1ab9321f-44bb-40a6-b114-6377b939f1be)

I will enable the bucket versioning and retry (will update the result later). If that's the root cause, please update the [deployment instructions](https://github.com/aws-samples/retail-demo-store/blob/master/docs/Deployment/getting-started.md)
> We recommend to create a dedicated bucket for deployment with versioning enabled.

It should be mandatory rather than recommended.

**Comment by jingnanl** [comment]
Update: the deployment succeeded after I enabled s3 bucket versioning.

**Comment by mridehalgh** [comment]
Thanks for the feedback @jingnanl - will get clearer wording out shortly.
