### ISSUE TITLE
CloudFormation Stack Failure: Issues with CustomCopyImagesLambdaFunction and CloudFront Resources

### ISSUE THREAD

**Issue by kobisystem** [aws-samples/retail-demo-store#649]
I am currently facing an issue while trying to deploy the CloudFormation stack associated with the Retail Demo Store. The stack fails during the creation of the resource CustomCopyImagesLambdaFunction and CloudFront. Below are the details:

Issues Encountered:
CustomCopyImagesLambdaFunction:

The resource fails to create, and I am unable to locate any logs or details that explain the root cause of the failure.
I have checked CloudWatch logs, the IAM role associated with the function, and the permissions. However, I cannot find anything that points to the exact issue.
CloudFront:

The stack also fails during the CloudFront resource creation.
I have ensured that the IAM user has sufficient permissions, including cloudfront:CreateDistribution and cloudfront:UpdateDistribution, but the stack still fails.
Steps Taken:
I have reviewed the CloudFormation events and resources for detailed logs but could not locate the root cause.
Verified permissions for both the Lambda function and CloudFront distribution creation.
I attempted to redeploy the stack multiple times, but the same issue persists.
Could you please assist in identifying what might be causing these failures? I would appreciate any insights or guidance on resolving these issues so that the deployment can proceed successfully.

Thank you for your attention to this matter. I look forward to your response.
![Screenshot 2024-10-10 at 14 45 09](https://github.com/user-attachments/assets/9dfc1d23-932e-409d-abf6-7fef67c68fa1)

**Comment by BastLeblanc** [comment]
Hi,

Can you look at the cloudwatch logs of the Copy Images Lambda function? 

Have you changed the parameter SourceImagesPackage to a specific URL?
