### ISSUE TITLE
link for local development instructions in Recommendations service README not working

### ISSUE THREAD

**Issue by MustaphaU** [aws-samples/retail-demo-store#651]
The current link for the local development instructions in the Recommendations service README (../) directs to `src`  instead of the correct path: https://github.com/aws-samples/retail-demo-store/blob/master/docs/Deployment/local-development/0-local-development-instructions.md.

**Comment by BastLeblanc** [comment]
fixed in #661  and others, use the doc linked here https://aws-samples.github.io/retail-demo-store/
