### ISSUE TITLE
AWS Evidently has been discontinued

### ISSUE THREAD

**Issue by helioribeiro** [aws-samples/retail-demo-store#665]
As I try to deploy the demo instance with CloudFormation following the official documentation, I get this error.

I tried to remove all the Evidently resources but it also didn't work.

<img width="1614" alt="image" src="https://github.com/user-attachments/assets/ffc64692-afc8-451b-8ab1-83c580d88360">

**Comment by BastLeblanc** [comment]
@helioribeiro Thanks for the issue reporting. It's now fixed in the main branch.

Feel free to reopen the issue if you still face any issues.
