### ISSUE TITLE
Incorrect copy destination in CopyImagesLambdaFunction

### ISSUE THREAD

**Issue by alexchirayath** [aws-samples/retail-demo-store#80]
I recently set up a deployment of the retail demo store using my own staging s3 buckets via the stage.sh script.
While the solution was deployed successfully, I am unable to see the images on the website.
On further researching, it seems that there is a bug in the CopyImagesLambdaFunction code.
The lambda function copies the files under **${RootURL}/${ResourceBucketRelativePath}images/** whereas the website is looking for the data under **${RootURL}/images/**

Proposed solution:  
The target object keys for the images needs to be updated to store in the root directory itself.
Change the logic in the lambda function would probably be [here](The target object keys for the images needs to be updated to store in the root directory itself.)

**Comment by BastLeblanc** [comment]
fix in PR #83 please review :)

**Comment by BastLeblanc** [comment]
updated fix in PR #84 please review :)

**Comment by BastLeblanc** [comment]
closing this issue as #84 was merged
